<?php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InstitutionsSeeder extends Seeder
{
    public function run()
    {
        // Düz metin isim listesi: (value="AAA-custom" olan "Diğer" için sadece "Diğer" kaydı ekliyoruz)
        $names = [
            'Diğer',
            'Adalet Bakanlığı',
            'Abdullah Gül Üniversitesi',
            'Afet ve Acil Durum Yönetimi Başkanlığı',
            'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
            'Adli Tıp Kurumu',
            'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
            'Ahiler Kalkınma Ajansı',
            'Adıyaman Üniversitesi',
            'Aile ve Sosyal Hizmetler Bakanlığı',
            'Afyon Kocatepe Üniversitesi',
            'Anayasa Mahkemesi Başkanlığı',
            'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
            'Ankara Kalkınma Ajansı',
            'Ağrı İbrahim Çeçen Üniversitesi',
            'Akaryakıt İkmal ve Nato Pol Tesisleri İşletme (ANT) Başkanlığı',
            'Akdeniz Üniversitesi',
            'Ankara Doğal Elektrik Üretim ve Ticaret A.Ş. Genel Müdürlüğü',
            'Aksaray Üniversitesi',
            'Ankara Ticaret Odası',
            'Alanya Alaaddin Keykubat Üniversitesi',
            'Atatürk Kültür, Dil ve Tarih Yüksek Kurumu Başkanlığı',
            'Alanya Üniversitesi',
            'Avrupa Birliği Başkanlığı',
            'Altınbaş Üniversitesi',
            'Avrupa Birliği Eğitim ve Gençlik Programları Merkezi Başkanlığı',
            'Amasya Üniversitesi',
            'Atatürk Orman Çiftliği Müdürlüğü',
            'Anadolu Üniversitesi',
            'Bankacılık Düzenleme ve Denetleme Kurumu',
            'Anka Teknoloji Üniversitesi',
            'Basın İlan Kurumu',
            'Ankara Bilim Üniversitesi',
            'Batı Karadeniz Kalkınma Ajansı',
            'Ankara Hacı Bayram Veli Üniversitesi',
            'Boru Hatları İle Petrol Taşıma A.Ş. Genel Müdürlüğü',
            'Ankara Medipol Üniversitesi',
            'Bankalararası Kart Merkezi',
            'Ankara Müzik ve Güzel Sanatlar Üniversitesi',
            'Batı Akdeniz Kalkınma Ajansı',
            'Ankara Sosyal Bilimler Üniversitesi',
            'Bilgi Teknolojileri ve İletişim Kurumu',
            'Ankara Üniversitesi',
            'Botaş International Genel Müdürlüğü',
            'Ankara Yıldırım Beyazıt Üniversitesi',
            'Bursa Eskişehir Bilecik Kalkınma Ajansı',
            'Antalya Belek Üniversitesi',
            'Cumhurbaşkanlığı',
            'Antalya Bilim Üniversitesi',
            'Cumhurbaşkanlığı Finans Ofisi Başkanlığı',
            'Ardahan Üniversitesi',
            'Cumhurbaşkanlığı Yatırım Ofisi',
            'Artvin Çoruh Üniversitesi',
            'Cumhurbaşkanlığı Dijital Dönüşüm Ofisi Başkanlığı',
            'Ataşehir Adıgüzel Meslek Yüksekokulu',
            'Cumhurbaşkanlığı İnsan Kaynakları Ofisi Başkanlığı',
            'Atatürk Üniversitesi',
            'Çalışma ve Sosyal Güvenlik Bakanlığı',
            'Atılım Üniversitesi',
            'Çalışma ve Sosyal Güvenlik Eğitim ve Araştırma Merkezi (ÇASGEM)',
            'Avrasya Üniversitesi',
            'Çanakkale Otoyol ve Köprüsü İnşaat Yatırım ve İşletme A.Ş.',
            'Aydın Adnan Menderes Üniversitesi',
            'Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı',
            'Bahçeşehir Üniversitesi',
            'Çay İşletmeleri Genel Müdürlüğü',
            'Balıkesir Üniversitesi',
            'Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
            'Bandırma Onyedi Eylül Üniversitesi',
            'Çukurova Kalkınma Ajansı',
            'Bartın Üniversitesi',
            'Danıştay Başkanlığı',
            'Başkent Üniversitesi',
            'Deniz Kuvvetleri Komutanlığı',
            'Batman Üniversitesi',
            'Devlet Hava Meydanları İşletmesi Genel Müdürlüğü',
            'Bayburt Üniversitesi',
            'Devlet Opera ve Balesi Genel Müdürlüğü',
            'Beykoz Üniversitesi',
            'Devlet Malzeme Ofisi Genel Müdürlüğü',
            'Bezm-i Âlem Vakıf Üniversitesi',
            'Devlet Arşivleri Başkanlığı',
            'Bilecik Şeyh Edebali Üniversitesi',
            'Darphane ve Damga Matbaası Genel Müdürlüğü',
            'Bingöl Üniversitesi',
            'Devlet Su İşleri Genel Müdürlüğü',
            'Biruni Üniversitesi',
            'Devlet Tiyatroları Genel Müdürlüğü',
            'Bitlis Eren Üniversitesi',
            'Boğaziçi Üniversitesi',
            'Dışişleri Bakanlığı',
            'Bolu Abant İzzet Baysal Üniversitesi',
            'Diyanet İşleri Başkanlığı',
            'Burdur Mehmet Akif Ersoy Üniversitesi',
            'Doğal Afet Sigortaları Kurumu',
            'Bursa Teknik Üniversitesi',
            'Doğu Akdeniz Kalkınma Ajansı',
            'Bursa Uludağ Üniversitesi',
            'Doğu Anadolu Kalkınma Ajansı',
            'Çağ Üniversitesi',
            'Doğu Anadolu Projesi Bölge Kalkınma İdaresi',
            'Çanakkale Onsekiz Mart Üniversitesi',
            'Doğu Karadeniz Kalkınma Ajansı',
            'Çankaya Üniversitesi',
            'Doğu Karadeniz Projesi Bölge Kalkınma İdaresi Başkanlığı',
            'Çankırı Karatekin Üniversitesi',
            'Doğu Marmara Kalkınma Ajansı',
            'Çukurova Üniversitesi',
            'e-Devlet Kapısı',
            'Demiroğlu Bilim Üniversitesi',
            'Emeklilik Gözetim Merkezi',
            'Dicle Üniversitesi',
            'Enerji Piyasaları İşletme A.Ş.',
            'Doğuş Üniversitesi',
            'Enerji ve Tabii Kaynaklar Bakanlığı',
            'Dokuz Eylül Üniversitesi',
            'Eti Maden İşletmeleri Genel Müdürlüğü',
            'Düzce Üniversitesi',
            'Elektrik Üretim A.Ş. Genel Müdürlüğü',
            'Ege Üniversitesi',
            'Emniyet Genel Müdürlüğü',
            'Erciyes Üniversitesi',
            'Enerji Piyasası Düzenleme Kurumu Başkanlığı',
            'Erzincan Binali Yıldırım Üniversitesi',
            'Erişim Sağlayıcıları Birliği',
            'Erzurum Teknik Üniversitesi',
            'Et ve Süt Kurumu Genel Müdürlüğü',
            'Eskişehir Osmangazi Üniversitesi',
            'Fırat Kalkınma Ajansı',
            'Eskişehir Teknik Üniversitesi',
            'Gelir İdaresi Başkanlığı',
            'Fatih Sultan Mehmet Vakıf Üniversitesi',
            'Göç İdaresi Başkanlığı',
            'Fenerbahçe Üniversitesi',
            'Gençlik ve Spor Bakanlığı',
            'Fırat Üniversitesi',
            'Güneydoğu Anadolu Projesi Bölge Kalkınma İdaresi Başkanlığı',
            'Galatasaray Üniversitesi',
            'Güney Ege Kalkınma Ajansı',
            'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
            'Güney Marmara Kalkınma Ajansı',
            'Gaziantep Üniversitesi',
            'Harita Genel Müdürlüğü',
            'Gebze Teknik Üniversitesi',
            'Hazine ve Maliye Bakanlığı',
            'Giresun Üniversitesi',
            'Hava Kuvvetleri Komutanlığı',
            'Gümüşhane Üniversitesi',
            'Helal Akreditasyon Kurumu Başkanlığı',
            'Hacettepe Üniversitesi',
            'İçişleri Bakanlığı',
            'Hakkari Üniversitesi',
            'İlksan',
            'Haliç Üniversitesi',
            'İstanbul Finans Merkezi',
            'Hatay Mustafa Kemal Üniversitesi',
            'İstanbul Ticaret Odası',
            'Harran Üniversitesi',
            'İzmir Kalkınma Ajansı',
            'Hasan Kalyoncu Üniversitesi',
            'İstanbul Kalkınma Ajansı',
            'Hitit Üniversitesi',
            'İller Bankası A.Ş.',
            'Iğdır Üniversitesi',
            'İletişim Başkanlığı',
            'Isparta Uygulamalı Bilimler Üniversitesi',
            'Jandarma Genel Komutanlığı',
            'Işık Üniversitesi',
            'Jandarma ve Sahil Güvenlik Akademisi',
            'İbn Haldun Üniversitesi',
            'Kamu Denetçiliği Kurumu',
            'İhsan Doğramacı Bilkent Üniversitesi',
            'Kamu İhale Kurumu',
            'İnönü Üniversitesi',
            'Kamu Gözetimi, Muhasebe ve Denetim Standartları Kurumu',
            'İskenderun Teknik Üniversitesi',
            'Karacadağ Kalkınma Ajansı',
            'İstanbul 29 Mayıs Üniversitesi',
            'Kara Kuvvetleri Komutanlığı',
            'İstanbul Arel Üniversitesi',
            'Kıyı Emniyeti Genel Müdürlüğü',
            'İstanbul Atlas Üniversitesi',
            'Konya Ovası Projesi Bölge Kalkınma İdaresi Başkanlığı',
            'İstanbul Aydın Üniversitesi',
            'Kuzeydoğu Anadolu Kalkınma Ajansı',
            'İstanbul Beykent Üniversitesi',
            'Kültür ve Turizm Bakanlığı',
            'İstanbul Bilgi Üniversitesi',
            'Kütüphaneler ve Yayımlar Genel Müdürlüğü',
            'İstanbul Esenyurt Üniversitesi',
            'Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı (KOSGEB)',
            'İstanbul Galata Üniversitesi',
            'Kuzey Anadolu Kalkınma Ajansı',
            'İstanbul Gedik Üniversitesi',
            'Kişisel Verileri Koruma Kurumu',
            'İstanbul Gelişim Üniversitesi',
            'Karayolları Genel Müdürlüğü',
            'İstanbul Kent Üniversitesi',
            'İstanbul Kültür Üniversitesi',
            'İstanbul Medeniyet Üniversitesi',
            'Maden Tetkik ve Arama Genel Müdürlüğü',
            'İstanbul Medipol Üniversitesi',
            'Makine ve Kimya Endüstrisi Anonim Şirketi',
            'İstanbul Nişantaşı Üniversitesi',
            'Merkezî Kayıt Kuruluşu A.Ş.',
            'İstanbul Okan Üniversitesi',
            'Meteoroloji Genel Müdürlüğü',
            'İstanbul Rumeli Üniversitesi',
            'Milli Eğitim Bakanlığı',
            'İstanbul Sabahattin Zaim Üniversitesi',
            'Milli Saraylar İdaresi Başkanlığı',
            'İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu',
            'Millî Savunma Bakanlığı',
            'İstanbul Sağlık ve Teknoloji Üniversitesi',
            'Milli Güvenlik Kurulu Genel Sekreterliği',
            'İstanbul Şişli Meslek Yüksekokulu',
            'Mevlana Kalkınma Ajansı',
            'İstanbul Teknik Üniversitesi',
            'Mesleki Yeterlilik Kurumu',
            'İstanbul Ticaret Üniversitesi',
            'Merkezi Finans ve İhale Birimi',
            'İstanbul Topkapı Üniversitesi',
            'Maden ve Petrol İşleri Genel Müdürlüğü',
            'İstanbul Üniversitesi',
            'Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü',
            'İstanbul Üniversitesi-Cerrahpaşa',
            'Nükleer Düzenleme Kurumu',
            'İstanbul Yeni Yüzyıl Üniversitesi',
            'Orman Genel Müdürlüğü',
            'İstinye Üniversitesi',
            'Orta Anadolu Kalkınma Ajansı',
            'İzmir Bakırçay Üniversitesi',
            'Orman Mühendisleri Odası',
            'İzmir Demokrasi Üniversitesi',
            'Orta Karadeniz Kalkınma Ajansı',
            'İzmir Ekonomi Üniversitesi',
            'Ölçme, Seçme ve Yerleştirme Merkezi (ÖSYM)',
            'İzmir Katip Çelebi Üniversitesi',
            'Özelleştirme İdaresi Başkanlığı',
            'İzmir Kavram Meslek Yüksekokulu',
            'Polis Akademisi Başkanlığı',
            'İzmir Tınaztepe Üniversitesi',
            'PTT',
            'İzmir Yüksek Teknoloji Enstitüsü',
            'Radyo ve Televizyon Üst Kurulu',
            'Kadir Has Üniversitesi',
            'Roketsan Roket Sanayi ve Ticaret A.Ş Genel Müdürlüğü',
            'Kafkas Üniversitesi',
            'Rekabet Kurumu',
            'Kahramanmaraş İstiklal Üniversitesi',
            'Sağlık Bakanlığı',
            'Kahramanmaraş Sütçü İmam Üniversitesi',
            'Sanayi ve Teknoloji Bakanlığı',
            'Kapadokya Üniversitesi',
            'Savunma Sanayii Başkanlığı',
            'Karabük Üniversitesi',
            'Serhat Kalkınma Ajansı',
            'Karadeniz Teknik Üniversitesi',
            'Sermaye Piyasası Lisanslama Sicil ve Eğitim Kuruluşu A.Ş.',
            'Karamanoğlu Mehmetbey Üniversitesi',
            'Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu',
            'Kastamonu Üniversitesi',
            'Sosyal Güvenlik Kurumu',
            'Kayseri Üniversitesi',
            'Sümer Holding A.Ş. Genel Müdürlüğü',
            'Kırıkkale Üniversitesi',
            'Strateji ve Bütçe Başkanlığı',
            'Kırklareli Üniversitesi',
            'Sivil Havacılık Genel Müdürlüğü',
            'Kırşehir Ahi Evran Üniversitesi',
            'Sigorta Bilgi ve Gözetim Merkezi',
            'Kilis 7 Aralık Üniversitesi',
            'Sermaye Piyasası Kurulu',
            'Kocaeli Sağlık ve Teknoloji Üniversitesi',
            'Sayıştay Başkanlığı',
            'Kocaeli Üniversitesi',
            'Savunma Sanayii Akademi',
            'Koç Üniversitesi',
            'Sahil Güvenlik Komutanlığı',
            'Konya Gıda ve Tarım Üniversitesi',
            'Takasbank İstanbul Takas ve Saklama Bankası A.Ş.',
            'Konya Teknik Üniversitesi',
            'Tarım İşletmeleri Genel Müdürlüğü',
            'KTO Karatay Üniversitesi',
            'Tapu ve Kadastro Genel Müdürlüğü',
            'Kütahya Dumlupınar Üniversitesi',
            'Tarım Sigortaları Havuzu',
            'Kütahya Sağlık Bilimleri Üniversitesi',
            'Tarım ve Kırsal Kalkınmayı Destekleme Kurumu Başkanlığı',
            'Lokman Hekim Üniversitesi',
            'Tasarruf Mevduatı Sigorta Fonu Başkanlığı',
            'Malatya Turgut Özal Üniversitesi',
            'TCDD Taşımacılık A.Ş. Genel Müdürlüğü',
            'Maltepe Üniversitesi',
            'TCDD',
            'Manisa Celâl Bayar Üniversitesi',
            'Toplu Konut İdaresi Başkanlığı (TOKİ)',
            'Mardin Artuklu Üniversitesi',
            'Tarım ve Orman Bakanlığı',
            'Marmara Üniversitesi',
            'TBMM Başkanlığı',
            'MEF Üniversitesi',
            'TCDD Teknik Mühendislik ve Müşavirlik A.Ş.',
            'Mersin Üniversitesi',
            'Ticaret Bakanlığı',
            'Mimar Sinan Güzel Sanatlar Üniversitesi',
            'Toprak Mahsulleri Ofisi',
            'Mudanya Üniversitesi',
            'Trakya Kalkınma Ajansı',
            'Muğla Sıtkı Koçman Üniversitesi',
            'Türk Akreditasyon Kurumu',
            'Munzur Üniversitesi',
            'TRT Genel Müdürlüğü',
            'Muş Alparslan Üniversitesi',
            'Türk Hava Kurumu',
            'Necmettin Erbakan Üniversitesi',
            'Türk İşbirliği ve Koordinasyon Ajansı Başkanlığı',
            'Nevşehir Hacı Bektaş Veli Üniversitesi',
            'Türkiye Bankalar Birliği',
            'Niğde Ömer Halisdemir Üniversitesi',
            'Türkiye Basketbol Federasyonu',
            'Nuh Naci Yazgan Üniversitesi',
            'Türkiye Belediyeler Birliği',
            'Ondokuz Mayıs Üniversitesi',
            'Türkiye Barolar Birliği',
            'Ordu Üniversitesi',
            'Türkiye Adalet Akademisi Başkanlığı',
            'Orta Doğu Teknik Üniversitesi',
            'Türkiye Bilimler Akademisi (TÜBA)',
            'Osmaniye Korkut Ata Üniversitesi',
            'Türkiye Cumhuriyet Merkez Bankası',
            'Ostim Teknik Üniversitesi',
            'Türkiye Elektrik Dağıtım A.Ş. Genel Müdürlüğü',
            'Özyeğin Üniversitesi',
            'Türkiye Elektromekanik Sanayii A.Ş. Genel Müdürlüğü',
            'Piri Reis Üniversitesi',
            'Türkiye Hayat ve Emeklilik Anonim Şirketi Genel Müdürlüğü',
            'Recep Tayyip Erdoğan Üniversitesi',
            'Türkiye Bilimsel ve Teknolojik Araştırma Kurumu (TÜBİTAK)',
            'Sabancı Üniversitesi',
            'Türkiye Değerleme Uzmanları Birliği',
            'Sağlık Bilimleri Üniversitesi',
            'Türkiye Elektrik İletim A.Ş. (TEİAŞ) Genel Müdürlüğü',
            'Sakarya Uygulamalı Bilimler Üniversitesi',
            'Türkiye Enerji Nükleer ve Maden Araştırma Kurumu',
            'Sakarya Üniversitesi',
            'Türkiye İhracatçılar Meclisi',
            'Samsun Üniversitesi',
            'Türkiye İnsan Hakları ve Eşitlik Kurumu Başkanlığı',
            'Sanko Üniversitesi',
            'Türkiye İş Kurumu (İŞKUR)',
            'Selçuk Üniversitesi',
            'Türkiye Katılım Bankaları Birliği',
            'Sivas Bilim ve Teknoloji Üniversitesi',
            'Türkiye Odalar ve Borsalar Birliği (TOBB)',
            'Sivas Cumhuriyet Üniversitesi',
            'Türkiye İstatistik Kurumu Başkanlığı (TÜİK)',
            'Süleyman Demirel Üniversitesi',
            'Türkiye Kalkınma ve Yatırım Bankası A.Ş',
            'Şırnak Üniversitesi',
            'Türkiye Kömür İşletmeleri Kurumu Genel Müdürlüğü',
            'Türkiye Noterler Birliği',
            'Tarsus Üniversitesi',
            'Türkiye Petrolleri Anonim Ortaklığı Genel Müdürlüğü',
            'TED Üniversitesi',
            'Türkiye Serbest Muhasebeci Mali Müşavirler ve Yeminli Mali Müşavirler Odaları Birliği',
            'Tekirdağ Namık Kemal Üniversitesi',
            'Türkiye Şeker Fabrikaları A.Ş',
            'TOBB Ekonomi ve Teknoloji Üniversitesi',
            'Türkiye Taşkömürü Kurumu Genel Müdürlüğü',
            'Tokat Gaziosmanpaşa Üniversitesi',
            'Türkiye Vücut Geliştirme, Fitness ve Bilek Güreşi',
            'Toros Üniversitesi',
            'Türkiye Yazma Eserler Kurumu Başkanlığı',
            'Trabzon Üniversitesi',
            'Türkiye Uzay Ajansı',
            'Trakya Üniversitesi',
            'Türkiye Tarım Kredi Kooperatifleri Merkez Birliği Genel Müdürlüğü',
            'Türk Hava Kurumu Üniversitesi',
            'Türkiye Sualtı Sporları Federasyonu',
            'Türk-Alman Üniversitesi',
            'Türkiye Ziraat Odaları Birliği Başkanlığı',
            'Türk-Japon Bilim ve Teknoloji Üniversitesi',
            'Türk Patent ve Marka Kurumu',
            'Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi',
            'Türk Standardları Enstitüsü',
            'Ufuk Üniversitesi',
            'Türk Silahlı Kuvvetlerini Güçlendirme Vakfı',
            'Uşak Üniversitesi',
            'Türk Kızılay',
            'Üsküdar Üniversitesi',
            'Ulaştırma ve Altyapı Bakanlığı',
            'Van Yüzüncü Yıl Üniversitesi',
            'Vakıflar Genel Müdürlüğü',
            'Yalova Üniversitesi',
            'Yargıtay Başkanlığı',
            'Yaşar Üniversitesi',
            'Yunus Emre Enstitüsü',
            'Yeditepe Üniversitesi',
            'Yükseköğretim Kalite Kurulu Başkanlığı',
            'Yıldız Teknik Üniversitesi',
            'Yüksek Seçim Kurulu Başkanlığı',
            'Yozgat Bozok Üniversitesi',
            'Yatırımcı Tazmin Merkezi',
            'Yüksek İhtisas Üniversitesi',
            'Yurtdışı Türkler ve Akraba Topluluklar Başkanlığı',
            'Zonguldak Bülent Ecevit Üniversitesi',
            'Yükseköğretim Kurulu Başkanlığı',
            'Zafer Kalkınma Ajansı',
            'Siirt Üniversitesi',
            'Türkiye Maarif Vakfı',
            'Sinop Üniversitesi',
        ];

        // Olası tekrarları temizle
        $names = array_values(array_unique($names));

        // Insert verisine çevir
        $data = array_map(fn ($n) => ['name' => $n], $names);

        // Batch insert (parçalayarak)
        $table = $this->db->table('institutions');
        $chunkSize = 200;
        foreach (array_chunk($data, $chunkSize) as $chunk) {
            $table->insertBatch($chunk);
        }
    }
}
